project:
  type: website
  output-dir: docs

website:
  title: "Learning Access Control - Themes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: access-control-foo.qmd
        text: Acces Control Foo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
